=== 3AMproductions/3amproductions.net/www/xml/ns/twix/twix.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- edited with XMLSpy v2006 U (http://www.altova.com) by Jason Karns (EMBRACE) -->
<xs:schema xmlns="http://3amproductions.net/xml/ns/twix/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xhtml="http://www.w3.org/1999/xhtml" targetNamespace="http://3amproductions.net/xml/ns/twix/" elementFormDefault="qualified">
	<xs:element name="portfolio">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="project" type="projectType" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="modified" type="xs:date" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="projectType">
		<xs:sequence>
			<xs:element name="started" type="xs:date"/>
			<xs:element name="modified" type="xs:date"/>
			<xs:element name="launched" type="xs:date" minOccurs="0"/>
			<xs:element name="organization" type="organizationType"/>
			<xs:element name="contacts" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="contactsType">
							<xs:sequence>
								<xs:element name="contact" type="contactType" minOccurs="0" maxOccurs="unbounded"/>
							</xs:sequence>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element ref="directory" minOccurs="0"/>
			<xs:element ref="subdomain" minOccurs="0"/>
			<xs:element ref="livesite" minOccurs="0"/>
			<xs:element name="notes" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="notesType">
							<xs:sequence>
								<xs:element ref="note" minOccurs="0" maxOccurs="unbounded"/>
							</xs:sequence>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="showcase" type="showcaseType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="id" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="class" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="3am"/>
					<xs:enumeration value="business"/>
					<xs:enumeration value="personal"/>
					<xs:enumeration value="probono"/>
					<xs:enumeration value="private"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="status" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="completed"/>
					<xs:enumeration value="draft"/>
					<xs:enumeration value="hold"/>
					<xs:enumeration value="managed"/>
					<xs:enumeration value="progress"/>
					<xs:enumeration value="terminated"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="manager" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="gil"/>
					<xs:enumeration value="jason"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="organizationType" mixed="true">
		<xs:attribute name="abbr" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="contactsType"/>
	<xs:complexType name="contactType">
		<xs:sequence>
			<xs:element ref="name"/>
			<xs:element ref="jobtitle" minOccurs="0"/>
			<xs:element ref="role" minOccurs="0"/>
			<xs:element ref="email" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element ref="phone" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="address" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="addressType">
							<xs:attribute name="type" use="required">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="home"/>
										<xs:enumeration value="work"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="addressType">
		<xs:sequence>
			<xs:element name="street1" type="street" minOccurs="0"/>
			<xs:element name="street2" type="street" minOccurs="0"/>
			<xs:element ref="city" minOccurs="0"/>
			<xs:element ref="state" minOccurs="0"/>
			<xs:element ref="zip" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="name" type="xs:string"/>
	<xs:element name="jobtitle" type="xs:string"/>
	<xs:element name="role" type="xs:string"/>
	<xs:element name="email">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="personal"/>
								<xs:enumeration value="business"/>
								<xs:enumeration value=""/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="phone">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="home"/>
								<xs:enumeration value="work"/>
								<xs:enumeration value="mobile"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="street">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:element name="city" type="xs:string"/>
	<xs:element name="state">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="abbr" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="OH"/>
								<xs:enumeration value="AL"/>
								<xs:enumeration value="AK"/>
								<xs:enumeration value="AS"/>
								<xs:enumeration value="AZ"/>
								<xs:enumeration value="AR"/>
								<xs:enumeration value="CA"/>
								<xs:enumeration value="CO"/>
								<xs:enumeration value="CT"/>
								<xs:enumeration value="DE"/>
								<xs:enumeration value="DC"/>
								<xs:enumeration value="FM"/>
								<xs:enumeration value="FL"/>
								<xs:enumeration value="GA"/>
								<xs:enumeration value="GU"/>
								<xs:enumeration value="HI"/>
								<xs:enumeration value="ID"/>
								<xs:enumeration value="IL"/>
								<xs:enumeration value="IN"/>
								<xs:enumeration value="IA"/>
								<xs:enumeration value="KS"/>
								<xs:enumeration value="KY"/>
								<xs:enumeration value="LA"/>
								<xs:enumeration value="ME"/>
								<xs:enumeration value="MH"/>
								<xs:enumeration value="MD"/>
								<xs:enumeration value="MA"/>
								<xs:enumeration value="MI"/>
								<xs:enumeration value="MN"/>
								<xs:enumeration value="MS"/>
								<xs:enumeration value="MO"/>
								<xs:enumeration value="MT"/>
								<xs:enumeration value="NE"/>
								<xs:enumeration value="NV"/>
								<xs:enumeration value="NH"/>
								<xs:enumeration value="NJ"/>
								<xs:enumeration value="NM"/>
								<xs:enumeration value="NY"/>
								<xs:enumeration value="NC"/>
								<xs:enumeration value="ND"/>
								<xs:enumeration value="MP"/>
								<xs:enumeration value="OH"/>
								<xs:enumeration value="OK"/>
								<xs:enumeration value="OR"/>
								<xs:enumeration value="PW"/>
								<xs:enumeration value="PA"/>
								<xs:enumeration value="PR"/>
								<xs:enumeration value="RI"/>
								<xs:enumeration value="SC"/>
								<xs:enumeration value="SD"/>
								<xs:enumeration value="TN"/>
								<xs:enumeration value="TX"/>
								<xs:enumeration value="UT"/>
								<xs:enumeration value="VT"/>
								<xs:enumeration value="VI"/>
								<xs:enumeration value="VA"/>
								<xs:enumeration value="WA"/>
								<xs:enumeration value="WV"/>
								<xs:enumeration value="WI"/>
								<xs:enumeration value="WY"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="zip">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d\d\d\d\d?(\-\d\d\d\d)"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="directory" type="xs:string"/>
	<xs:element name="subdomain" type="xs:string"/>
	<xs:element name="livesite" type="xs:anyURI"/>
	<xs:complexType name="notesType"/>
	<xs:element name="note">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="modified" type="xs:date" use="required"/>
					<xs:attribute name="by" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="title" type="xs:string"/>
	<xs:complexType name="showcaseType">
		<xs:sequence>
			<xs:element ref="title"/>
			<xs:element name="description" type="descriptionType"/>
			<xs:element name="images" type="imagesType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="descriptionType" mixed="true">
		<xs:choice>
			<xs:any namespace="http://www.w3.org/1999/xhtml" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</xs:choice>
	</xs:complexType>
	<xs:element name="description" type="descriptionType"/>
	<xs:complexType name="imagesType">
		<xs:sequence>
			<xs:element name="feature" type="featureType"/>
			<xs:element name="screenshot" type="screenshotType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="featureType">
		<xs:sequence>
			<xs:element ref="src" minOccurs="0"/>
			<xs:element ref="thumbnail" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="screenshotType">
		<xs:sequence>
			<xs:element ref="src" minOccurs="0"/>
			<xs:element ref="thumbnail" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="src" type="xs:string"/>
	<xs:element name="thumbnail" type="xs:string"/>
</xs:schema>

=== 3AMproductions/3amproductions.net/www/xml/twilight/.backup/portfolio-2007-05-09T10-33-25.xml
<?xml version="1.0" encoding="UTF-8"?>
<portfolio modified="2006-08-24" xmlns="http://3amproductions.net/xml/ns/twix/" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://3amproductions.net/xml/ns/twix/ http://3amproductions.net/xml/ns/twix/twix.xsd">
	<project id="threeamv1" class="3am" status="completed">
		<started>2005-05-01</started>
		<modified>2005-05-07</modified>
		<launched>2005-05-07</launched>
		<organization abbr="3am">3AM Productions</organization>
		<contacts>
			<contact>
				<name>Jason Karns</name>
				<email type="business">jason@3amproductions.net</email>
			</contact>
			<contact>
				<name>Gilbert Velasquez</name>
				<email type="business">gilbert@3amproductions.net</email>
			</contact>
		</contacts>
		<directory>threeam</directory>
		<subdomain>threeam</subdomain>
		<livesite>http://threeam.3amproductions.net</livesite>
		<showcase>
			<title>3AM Productions v1.0</title>
			<description>This is the original site that 3AM Productions began with. We choose a color scheme that we liked to reflect our personality and the name of our company. In one week we went from having nothing to what you see here. We used this as an opportunity to create a site under pressure.</description>
			<images>
				<feature>
					<thumbnail>http://3amproductions.net/images/3AMv1.gif</thumbnail>
				</feature>
				<screenshot>
					<src>http://3amproductions.net/images/3big01.gif</src>
					<thumbnail>http://3amproductions.net/images/3alt01.gif</thumbnail>
				</screenshot>
				<screenshot>
					<src>http://3amproductions.net/images/3big02.gif</src>
					<thumbnail>http://3amproductions.net/images/3alt02.gif</thumbnail>
				</screenshot>
				<screenshot>
					<src>http://3amproductions.net/images/3big03.gif</src>
					<thumbnail>http://3amproductions.net/images/3alt03.gif</thumbnail>
				</screenshot>
			</images>
		</showcase>
	</project>
	<project id="threeamv2" class="3am" status="managed">
		<started>2006-04-01</started>
		<modified>2006-05-01</modified>
		<launched>2006-05-01</launched>
		<organization abbr="3am">3AM Productions</organization>
		<contacts>
			<contact>
				<name>Jason Karns</name>
				<email type="business">jason@3amproductions.net</email>
			</contact>
			<contact>
				<name>Gilbert Velasquez</name>
				<email type="business">gilbert@3amproductions.net</email>
			</contact>
		</contacts>
		<directory>3am</directory>
		<livesite>http://3amproductions.net</livesite>
		<showcase>
			<title>3AM Productions v2.0</title>
			<description>This is our current site which we made as an update and also to be a part of the <xhtml:a href="http://www.cssreboot.com" title="see the reboots" rel="external">May 2006 CSS Reboot</xhtml:a>. We have gone with a minimalistic approach giving the user a bold visual experience while separating the content without the use of heavy images.</description>
			<images>
				<feature>
					<thumbnail>http://3amproductions.net/images/3AMv2.gif</thumbnail>
				</feature>
				<screenshot>
					<src>http://3amproductions.net/images/3v2big01.gif</src>
					<thumbnail>http://3amproductions.net/images/3v2alt01.gif</thumbnail>
				</screenshot>
				<screenshot>
					<src>http://3amproductions.net/images/3v2big02.gif</src>
					<thumbnail>http://3amproductions.net/images/3v2alt02.gif</thumbnail>
				</screenshot>
				<screenshot>
					<src>http://3amproductions.net/images/3v2big03.gif</src>
					<thumbnail>http://3amproductions.net/images/3v2alt03.gif</thumbnail>
				</screenshot>
			</images>
		</showcase>
	</project>
	<project id="argentum" class="business" status="terminated" manager="jason">
		<started>2004-03-01</started>
		<modified>2004-03-01</modified>
		<organization>Argentum</organization>
		<directory>argentum</directory>
	</project>
	<project id="ghsnhs" class="business" status="terminated" manager="jason">
		<started>2001-11-01</started>
		<modified>2001-11-01</modified>
		<organization abbr="GNHS">Graham HS National Honor Society</organization>
		<directory>nhs</directory>
	</project>
	<project id="caduceus" class="business" status="terminated" manager="jason">
		<started>2004-09-01</started>
		<modified>2004-09-01</modified>
		<organization abbr="CadCorp">The Caduceus Corporation</organization>
		<contacts>
			<contact>
				<name>Kenneth Ryan</name>
				<email type="personal">tcckcr@yahoo.com</email>
			</contact>
		</contacts>
		<directory>caduceus</directory>
		<subdomain>caduceus</subdomain>
		<livesite>http://www.needle-zapper.com</livesite>
	</project>
	<project id="arts" class="business" status="terminated" manager="jason">
		<started>2005-06-25</started>
		<modified>2005-06-25</modified>
		<organization>Gibson Crafts</organization>
		<contacts>
			<contact>
				<name>Tammy Gibson</name>
				<email type="personal">megib@netzero.com</email>
			</contact>
		</contacts>
	</project>
	<project id="perceptionist" class="business" status="terminated" manager="gil">
		<started>2005-01-01</started>
		<modified>2005-01-01</modified>
		<organization>Perceptionist Inc.</organization>
		<contacts>
			<contact>
				<name>Tiger Downey</name>
				<email type="business">tigerd@perceptionistinc.com</email>
			</contact>
		</contacts>
		<directory>perceptionist</directory>
		<subdomain>perceptionist</subdomain>
		<livesite>http://www.myperceptionist.com</livesite>
	</project>
	<project id="ghsband" class="probono" status="managed" manager="jason">
		<started>2000-08-01</started>
		<modified>2005-11-21</modified>
		<launched>2000-08-01</launched>
		<organization>Graham Band</organization>
		<contacts>
			<contact>
				<name>Jason Karns</name>
				<email type="business">ghsband@ctcn.net</email>
			</contact>
		</contacts>
		<directory>band</directory>
		<livesite>http://www.grahamband.com/</livesite>
	</project>
	<project id="ghsaa" class="probono" status="draft" manager="jason">
		<started>2002-06-09</started>
		<modified>2002-06-09</modified>
		<organization abbr="GHSAA">Graham HS Alumni Association</organization>
		<contacts>
			<contact>
				<name>Roberta Vetters</name>
				<email type="personal">birtiev@hotmail.com</email>
			</contact>
		</contacts>
		<directory>ghsaa</directory>
		<subdomain>ghsaa</subdomain>
	</project>
	<project id="lso" class="probono" status="draft" manager="gil">
		<started>2005-10-01</started>
		<modified>2006-10-05</modified>
		<organization abbr="LSO">The Libertarian Studies Organization</organization>
		<contacts>
			<contact>
				<name>Brandon Dobyns</name>
				<email type="personal">dobyns.5@osu.edu</email>
			</contact>
		</contacts>
		<directory>lso</directory>
		<livesite>http://lso.org.ohio-state.edu/</livesite>
	</project>
	<project id="legs" class="private" status="managed" manager="jason">
		<started>2002-01-17</started>
		<modified>2004-09-17</modified>
		<launched>2002-01-17</launched>
		<organization abbr="Legs">The Legs and the Woman</organization>
		<contacts>
			<contact>
				<name>Brandon Dobyns</name>
				<email type="personal">dobyns.5@osu.edu</email>
			</contact>
		</contacts>
		<directory>legs</directory>
		<livesite>http://thesanctuary.bravepages.com/legs</livesite>
	</project>
	<project id="sanctuary" class="private" status="managed" manager="jason">
		<started>2001-03-30</started>
		<modified>2002-08-01</modified>
		<launched>2001-03-30</launched>
		<organization>The Sanctuary</organization>
		<contacts>
			<contact>
				<name>Jason Karns</name>
				<email type="personal">karnsj@cse.ohio-state.edu</email>
			</contact>
		</contacts>
		<directory>sanctuary</directory>
		<livesite>http://thesanctuary.bravepages.com</livesite>
	</project>
	<project id="jelloshot" class="private" status="draft" manager="gil">
		<started>2006-01-01</started>
		<modified>2006-01-01</modified>
		<organization>JelloShot.com</organization>
		<contacts>
			<contact>
				<name>Gilbert Velasquez</name>
				<email type="business">gilbert@3amproductions.net</email>
			</contact>
		</contacts>
		<subdomain>jelloshot</subdomain>
		<showcase>
			<title>JelloShot.com</title>
			<description>This site was a mockup created as part of a project for an information systems class. This is the first iteration of a new compnay idea being proposed by that group. It was targeted to the college age group and so the colors are very strong and bold with catchy images the market can relate to.</description>
			<images>
				<feature>
					<thumbnail>http://3amproductions.net/images/JelloShotv1.gif</thumbnail>
				</feature>
				<screenshot>
					<src>http://3amproductions.net/images/Jbig01.gif</src>
					<thumbnail>http://3amproductions.net/images/Jalt01.gif</thumbnail>
				</screenshot>
				<screenshot>
					<src>http://3amproductions.net/images/Jbig02.gif</src>
					<thumbnail>http://3amproductions.net/images/Jalt02.gif</thumbnail>
				</screenshot>
				<screenshot>
					<src>http://3amproductions.net/images/Jbig03.gif</src>
					<thumbnail>http://3amproductions.net/images/Jalt03.gif</thumbnail>
				</screenshot>
			</images>
		</showcase>
	</project>
	<project id="ipokr" class="personal" status="hold" manager="gil">
		<started>2006-04-01</started>
		<modified>2006-07-12</modified>
		<organization abbr="iPokr">iPokr International</organization>
		<contacts>
			<contact>
				<name>Jason Karns</name>
				<email type="personal">karnsj@cse.ohio-state.edu</email>
			</contact>
			<contact>
				<name>Mike Busch</name>
				<email type="personal">busch@cse.ohio-state.edu</email>
			</contact>
			<contact>
				<name>Scott Bickel</name>
				<email type="personal">bickels@cse.ohio-state.edu</email>
			</contact>
		</contacts>
		<directory>ipokr</directory>
		<subdomain>ipokr</subdomain>
	</project>
	<project id="latinostudies" class="personal" status="completed" manager="gil">
		<started>2006-01-01</started>
		<modified>2006-04-01</modified>
		<launched>2006-04-01</launched>
		<organization abbr="LatinoStudies">Latino Studies</organization>
		<contacts>
			<contact>
				<name>Gilbert Velasquez</name>
